function [x, y, d] = sim_estimation(cal_dist, cal_span_x, cal_span_y, ...
                                    view_angle_x, view_angle_y, ...
                                    offset_x, offset_y, distance, ...
                                    bias, noise, ...
                                    use_meters, do_plot)
if nargin <= 10
  use_meters = false
end

reference_points = get_reference_points(use_meters);
normalized_reference_points =  [ ...
    2 * reference_points(:, 1)' / cal_span_x; ...
    2 * reference_points(:, 2)' / cal_span_y ]';
projected_points = project_points(cal_dist, cal_span_x, cal_span_y, ...
                                  view_angle_x, view_angle_y, ...
                                  offset_x, offset_y, distance, ...
                                  use_meters);
observed_points = add_error(projected_points, bias, noise);
if nargin > 11
  if do_plot
    plot(normalized_reference_points(:, 1), ...
         normalized_reference_points(:, 2), 'x', ...
         observed_points(:, 1), observed_points(:, 2), 'o')
    grid
  end
end
% TODO: actually simulate here
